[package]
name = "solar-rust"
version = "0.1.0"
authors = ["pierreyoda <pierreyoda@users.noreply.github.com>"]

[lib]
name = "solar_rustlib"
path = "src/lib.rs"

[[bin]]
name = "solar-rust"
path = "src/bin/main.rs"

[dependencies]
rand = "0.3.14"
piston_window = "0.45.0"
piston2d-graphics = "0.16.0"
piston2d-gfx_graphics = "0.27.0"
